on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/sync.yml'

name: Update universe

# Do not launch new job before the old one is done
concurrency: ${{ github.workflow }}

jobs:
  update:
    name: Update submodules
    uses: r-universe-org/workflows/.github/workflows/sync.yml@v3
    secrets:
      GH_APP_KEY: ${{ secrets.GH_APP_KEY }}
      BOT_TOKEN: ${{ secrets.GHPAT }}
